//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlgoStudio.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TealSharp smart contracts do not yet support subroutines..
        /// </summary>
        internal static string E000Description {
            get {
                return ResourceManager.GetString("E000Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The class {0} declares subroutines, which are not yet supported. {1}.
        /// </summary>
        internal static string E000MessageFormat {
            get {
                return ResourceManager.GetString("E000MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported subroutines..
        /// </summary>
        internal static string E000Title {
            get {
                return ResourceManager.GetString("E000Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TealSharp programs do not suppport nested types..
        /// </summary>
        internal static string E001Description {
            get {
                return ResourceManager.GetString("E001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested {0} type is not supported in smart contracts. {1}.
        /// </summary>
        internal static string E001MessageFormat {
            get {
                return ResourceManager.GetString("E001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested types are not supported in smart contracts..
        /// </summary>
        internal static string E001Title {
            get {
                return ResourceManager.GetString("E001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TealSharp is a subset of CSharp. Error level diagnostics must first be corrected..
        /// </summary>
        internal static string E002Description {
            get {
                return ResourceManager.GetString("E002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are base CSharp error level diagnostics, which must be corrected first.{1}.
        /// </summary>
        internal static string E002MessageFormat {
            get {
                return ResourceManager.GetString("E002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base CSharp compilation must be corrected..
        /// </summary>
        internal static string E002Title {
            get {
                return ResourceManager.GetString("E002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many fields or local variables: teal is restricted to a scratch space size of 256..
        /// </summary>
        internal static string E003Description {
            get {
                return ResourceManager.GetString("E003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many fields or local variables: teal is restricted to a scratch space size of 256.{1}.
        /// </summary>
        internal static string E003MessageFormat {
            get {
                return ResourceManager.GetString("E003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scratch space size exceeded..
        /// </summary>
        internal static string E003Title {
            get {
                return ResourceManager.GetString("E003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field or local variable was not found in scratch space..
        /// </summary>
        internal static string E004Description {
            get {
                return ResourceManager.GetString("E004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable {0} is missing from the symbol table. This could indicate unsupported code structure.{1}.
        /// </summary>
        internal static string E004MessageFormat {
            get {
                return ResourceManager.GetString("E004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol not found..
        /// </summary>
        internal static string E004Title {
            get {
                return ResourceManager.GetString("E004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported syntax for smart contract generation..
        /// </summary>
        internal static string E006Description {
            get {
                return ResourceManager.GetString("E006Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This syntax {0} is not currently supported for contract generation.{1}.
        /// </summary>
        internal static string E006MessageFormat {
            get {
                return ResourceManager.GetString("E006MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported syntax..
        /// </summary>
        internal static string E006Title {
            get {
                return ResourceManager.GetString("E006Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage variables must be declared in the class scope..
        /// </summary>
        internal static string E007Description {
            get {
                return ResourceManager.GetString("E007Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The variable {0} is declared as a storage variable, which must be declared in the smart contract class scope. {1}.
        /// </summary>
        internal static string E007MessageFormat {
            get {
                return ResourceManager.GetString("E007MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage variables cannot be local..
        /// </summary>
        internal static string E007Title {
            get {
                return ResourceManager.GetString("E007Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type is not supported by this version of the tooling..
        /// </summary>
        internal static string E008Description {
            get {
                return ResourceManager.GetString("E008Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is is not supported by this version.{1}.
        /// </summary>
        internal static string E008MessageFormat {
            get {
                return ResourceManager.GetString("E008MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type..
        /// </summary>
        internal static string E008Title {
            get {
                return ResourceManager.GetString("E008Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected symbol type. This could indicate an unsupported language feature..
        /// </summary>
        internal static string E009Description {
            get {
                return ResourceManager.GetString("E009Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The internal symbol type {0} is not usable here.{1}.
        /// </summary>
        internal static string E009MessageFormat {
            get {
                return ResourceManager.GetString("E009MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported symbol type here..
        /// </summary>
        internal static string E009Title {
            get {
                return ResourceManager.GetString("E009Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subroutines must be declared as part of a program..
        /// </summary>
        internal static string E010Description {
            get {
                return ResourceManager.GetString("E010Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} subroutine must be declared local to a program.{1}.
        /// </summary>
        internal static string E010MessageFormat {
            get {
                return ResourceManager.GetString("E010MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No global subroutines..
        /// </summary>
        internal static string E010Title {
            get {
                return ResourceManager.GetString("E010Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable assignments must occur in the context of a program. .
        /// </summary>
        internal static string E011Description {
            get {
                return ResourceManager.GetString("E011Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable {0} assignment must occur in the context of a program.{1}.
        /// </summary>
        internal static string E011MessageFormat {
            get {
                return ResourceManager.GetString("E011MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No global variable assignments..
        /// </summary>
        internal static string E011Title {
            get {
                return ResourceManager.GetString("E011Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error..
        /// </summary>
        internal static string E012Description {
            get {
                return ResourceManager.GetString("E012Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.{1}.
        /// </summary>
        internal static string E012MessageFormat {
            get {
                return ResourceManager.GetString("E012MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error..
        /// </summary>
        internal static string E012Title {
            get {
                return ResourceManager.GetString("E012Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported invocation type for smart contracts..
        /// </summary>
        internal static string E013Description {
            get {
                return ResourceManager.GetString("E013Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported invocation type {0} for smart contracts.{1}.
        /// </summary>
        internal static string E013MessageFormat {
            get {
                return ResourceManager.GetString("E013MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported invocation type..
        /// </summary>
        internal static string E013Title {
            get {
                return ResourceManager.GetString("E013Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A smart contract cannot be called recursively.
        /// </summary>
        internal static string E014Description {
            get {
                return ResourceManager.GetString("E014Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A smart contract cannot be called recursively.{1}.
        /// </summary>
        internal static string E014MessageFormat {
            get {
                return ResourceManager.GetString("E014MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A smart contract cannot be called recursively..
        /// </summary>
        internal static string E014Title {
            get {
                return ResourceManager.GetString("E014Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function is not visible..
        /// </summary>
        internal static string E015Description {
            get {
                return ResourceManager.GetString("E015Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The function {0} cannot be called as it is not visible.{1}.
        /// </summary>
        internal static string E015MessageFormat {
            get {
                return ResourceManager.GetString("E015MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported function visibility..
        /// </summary>
        internal static string E015Title {
            get {
                return ResourceManager.GetString("E015Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked and unchecked are not supported in this version. Compile time declarations are checked and runtime evaluation is unchecked..
        /// </summary>
        internal static string E016Description {
            get {
                return ResourceManager.GetString("E016Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked and unchecked are not supported in this version. Compile time declarations are checked and runtime evaluation is unchecked.{1}.
        /// </summary>
        internal static string E016MessageFormat {
            get {
                return ResourceManager.GetString("E016MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked and unchecked unsupported..
        /// </summary>
        internal static string E016Title {
            get {
                return ResourceManager.GetString("E016Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator unsupported in this context..
        /// </summary>
        internal static string E017Description {
            get {
                return ResourceManager.GetString("E017Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator unsupported in this context.{1}.
        /// </summary>
        internal static string E017MessageFormat {
            get {
                return ResourceManager.GetString("E017MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported operator usage..
        /// </summary>
        internal static string E017Title {
            get {
                return ResourceManager.GetString("E017Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref and out parameters are not permitted for ABI methods..
        /// </summary>
        internal static string E018Description {
            get {
                return ResourceManager.GetString("E018Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref and out parameters are not permitted for ABI methods.{1}.
        /// </summary>
        internal static string E018MessageFormat {
            get {
                return ResourceManager.GetString("E018MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal ref or out parameter..
        /// </summary>
        internal static string E018Title {
            get {
                return ResourceManager.GetString("E018Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvokeSmartContract boilerplate used in incorrect scope..
        /// </summary>
        internal static string E019Description {
            get {
                return ResourceManager.GetString("E019Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvokeSmartContract boilerplate used in incorrect scope.{1}.
        /// </summary>
        internal static string E019MessageFormat {
            get {
                return ResourceManager.GetString("E019MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvokeSmartContract boilerplate used in incorrect scope..
        /// </summary>
        internal static string E019Title {
            get {
                return ResourceManager.GetString("E019Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member accesss expressions must be of a Simple kind..
        /// </summary>
        internal static string E020Description {
            get {
                return ResourceManager.GetString("E020Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member accesss expressions must be of a Simple kind: {0}.{1}.
        /// </summary>
        internal static string E020MessageFormat {
            get {
                return ResourceManager.GetString("E020MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member accesss expressions must be of a Simple kind..
        /// </summary>
        internal static string E020Title {
            get {
                return ResourceManager.GetString("E020Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scratch space variables for referenced types are not yet supported..
        /// </summary>
        internal static string E021Description {
            get {
                return ResourceManager.GetString("E021Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scratch space variables for referenced types are not yet supported.{1}.
        /// </summary>
        internal static string E021MessageFormat {
            get {
                return ResourceManager.GetString("E021MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scratch space variables for referenced types are not yet supported..
        /// </summary>
        internal static string E021Title {
            get {
                return ResourceManager.GetString("E021Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference smart contract method arguments must be declared as &apos;in&apos;..
        /// </summary>
        internal static string E022Description {
            get {
                return ResourceManager.GetString("E022Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference smart contract method arguments must be declared as &apos;in&apos; : {0}.{1}.
        /// </summary>
        internal static string E022MessageFormat {
            get {
                return ResourceManager.GetString("E022MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference smart contract method arguments must be declared as &apos;in&apos;..
        /// </summary>
        internal static string E022Title {
            get {
                return ResourceManager.GetString("E022Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorand external references cannot yet be directly used..
        /// </summary>
        internal static string E023Description {
            get {
                return ResourceManager.GetString("E023Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorand external references cannot yet be directly used: {0}.{1}.
        /// </summary>
        internal static string E023MessageFormat {
            get {
                return ResourceManager.GetString("E023MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorand external references cannot yet be directly used..
        /// </summary>
        internal static string E023Title {
            get {
                return ResourceManager.GetString("E023Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes to external references are not permitted..
        /// </summary>
        internal static string E024Description {
            get {
                return ResourceManager.GetString("E024Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writes to external references are not permitted: {0}.{1}.
        /// </summary>
        internal static string E024MessageFormat {
            get {
                return ResourceManager.GetString("E024MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External write not permitted..
        /// </summary>
        internal static string E024Title {
            get {
                return ResourceManager.GetString("E024Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member access expressions are not permitted in this context..
        /// </summary>
        internal static string E025Description {
            get {
                return ResourceManager.GetString("E025Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member access expressions are not permitted in this context. {0}.{1}.
        /// </summary>
        internal static string E025MessageFormat {
            get {
                return ResourceManager.GetString("E025MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal member access..
        /// </summary>
        internal static string E025Title {
            get {
                return ResourceManager.GetString("E025Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound assignment operators are not yet supported..
        /// </summary>
        internal static string E026Description {
            get {
                return ResourceManager.GetString("E026Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound assignment operators are not yet supported.{1}.
        /// </summary>
        internal static string E026MessageFormat {
            get {
                return ResourceManager.GetString("E026MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound assignment operators are not yet supported..
        /// </summary>
        internal static string E026Title {
            get {
                return ResourceManager.GetString("E026Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null literals are not supported here..
        /// </summary>
        internal static string E027Description {
            get {
                return ResourceManager.GetString("E027Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null literals are not supported here.{1}.
        /// </summary>
        internal static string E027MessageFormat {
            get {
                return ResourceManager.GetString("E027MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null literals are not supported here..
        /// </summary>
        internal static string E027Title {
            get {
                return ResourceManager.GetString("E027Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional parameters are not supported in method or function calls. There was a mismatch between argument count and parameter count..
        /// </summary>
        internal static string E028Description {
            get {
                return ResourceManager.GetString("E028Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional parameters are not supported in method or function calls. There was a mismatch between argument count and parameter count..{0}.
        /// </summary>
        internal static string E028MessageFormat {
            get {
                return ResourceManager.GetString("E028MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional parameters are not supported in method or function calls..
        /// </summary>
        internal static string E028Title {
            get {
                return ResourceManager.GetString("E028Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named optional parameters are not supported. .
        /// </summary>
        internal static string E029Description {
            get {
                return ResourceManager.GetString("E029Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named optional parameters are not supported. {0}.
        /// </summary>
        internal static string E029MessageFormat {
            get {
                return ResourceManager.GetString("E029MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named optional parameters are not supported..
        /// </summary>
        internal static string E029Title {
            get {
                return ResourceManager.GetString("E029Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null arguments are only valid for predefined optional parameters..
        /// </summary>
        internal static string E030Description {
            get {
                return ResourceManager.GetString("E030Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null arguments are only valid for predefined optional parameters. {0}.
        /// </summary>
        internal static string E030MessageFormat {
            get {
                return ResourceManager.GetString("E030MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null arguments are only valid for predefined optional parameters..
        /// </summary>
        internal static string E030Title {
            get {
                return ResourceManager.GetString("E030Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array creation is not yet supported. Please use {} initialisers..
        /// </summary>
        internal static string E031Description {
            get {
                return ResourceManager.GetString("E031Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array creation is not yet supported. Please use {} initialisers. {0}.
        /// </summary>
        internal static string E031MessageFormat {
            get {
                return ResourceManager.GetString("E031MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported array creation..
        /// </summary>
        internal static string E031Title {
            get {
                return ResourceManager.GetString("E031Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array method not yet supported..
        /// </summary>
        internal static string E032Description {
            get {
                return ResourceManager.GetString("E032Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array method not yet supported {0}.
        /// </summary>
        internal static string E032MessageFormat {
            get {
                return ResourceManager.GetString("E032MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported array method..
        /// </summary>
        internal static string E032Title {
            get {
                return ResourceManager.GetString("E032Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be literal or constant..
        /// </summary>
        internal static string E033Description {
            get {
                return ResourceManager.GetString("E033Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be literal or constant..
        /// </summary>
        internal static string E033MessageFormat {
            get {
                return ResourceManager.GetString("E033MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument must be literal or constant..
        /// </summary>
        internal static string E033Title {
            get {
                return ResourceManager.GetString("E033Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last transaction reference must be an AppCallTransactionReference..
        /// </summary>
        internal static string E034Description {
            get {
                return ResourceManager.GetString("E034Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last transaction reference must be an AppCallTransactionReference..
        /// </summary>
        internal static string E034MessageFormat {
            get {
                return ResourceManager.GetString("E034MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last transaction reference must be an AppCallTransactionReference..
        /// </summary>
        internal static string E034Title {
            get {
                return ResourceManager.GetString("E034Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method or function calls are not permitted during an Inner Transaction..
        /// </summary>
        internal static string E035Description {
            get {
                return ResourceManager.GetString("E035Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method or function calls are not permitted during an Inner Transaction. {0}.
        /// </summary>
        internal static string E035MessageFormat {
            get {
                return ResourceManager.GetString("E035MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No calls during Inner Transaction..
        /// </summary>
        internal static string E035Title {
            get {
                return ResourceManager.GetString("E035Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group transaction must only contain transactions..
        /// </summary>
        internal static string E036Description {
            get {
                return ResourceManager.GetString("E036Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group transaction must only contain transactions.{0}.
        /// </summary>
        internal static string E036MessageFormat {
            get {
                return ResourceManager.GetString("E036MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group transaction must only contain transactions..
        /// </summary>
        internal static string E036Title {
            get {
                return ResourceManager.GetString("E036Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner transaction results cannot be transferred..
        /// </summary>
        internal static string E037Description {
            get {
                return ResourceManager.GetString("E037Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner transaction results cannot be transferred..
        /// </summary>
        internal static string E037MessageFormat {
            get {
                return ResourceManager.GetString("E037MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner transaction results cannot be transferred..
        /// </summary>
        internal static string E037Title {
            get {
                return ResourceManager.GetString("E037Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner transaction cannot be assigned more than once in an Inner Transaction scope..
        /// </summary>
        internal static string E038Description {
            get {
                return ResourceManager.GetString("E038Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner transaction cannot be assigned more than once in an Inner Transaction scope..
        /// </summary>
        internal static string E038MessageFormat {
            get {
                return ResourceManager.GetString("E038MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner transaction cannot be assigned more than once in an Inner Transaction scope..
        /// </summary>
        internal static string E038Title {
            get {
                return ResourceManager.GetString("E038Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App calls are inner transactions and must be executed in an inner transaction local function..
        /// </summary>
        internal static string E039Description {
            get {
                return ResourceManager.GetString("E039Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App calls are inner transactions and must be executed in an inner transaction local function..
        /// </summary>
        internal static string E039MessageFormat {
            get {
                return ResourceManager.GetString("E039MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App calls are inner transactions and must be executed in an inner transaction local function..
        /// </summary>
        internal static string E039Title {
            get {
                return ResourceManager.GetString("E039Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App reference calls are not permitted to have more than one return value..
        /// </summary>
        internal static string E040Description {
            get {
                return ResourceManager.GetString("E040Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App reference calls are not permitted to have more than one return value..
        /// </summary>
        internal static string E040MessageFormat {
            get {
                return ResourceManager.GetString("E040MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App reference calls are not permitted to have more than one return value..
        /// </summary>
        internal static string E040Title {
            get {
                return ResourceManager.GetString("E040Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartContractReference methods must have a SmartContractMethod attribute..
        /// </summary>
        internal static string E041Description {
            get {
                return ResourceManager.GetString("E041Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartContractReference methods must have a SmartContractMethod attribute..
        /// </summary>
        internal static string E041MessageFormat {
            get {
                return ResourceManager.GetString("E041MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartContractReference methods must have a SmartContractMethod attribute..
        /// </summary>
        internal static string E041Title {
            get {
                return ResourceManager.GetString("E041Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerTransactionCalls cannot be nested. Nested inner transaction calls are expressed as nested ValueTuples..
        /// </summary>
        internal static string E042Description {
            get {
                return ResourceManager.GetString("E042Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerTransactionCalls cannot be nested. Nested inner transaction calls are expressed as nested ValueTuples..
        /// </summary>
        internal static string E042MessageFormat {
            get {
                return ResourceManager.GetString("E042MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerTransactionCalls cannot be nested..
        /// </summary>
        internal static string E042Title {
            get {
                return ResourceManager.GetString("E042Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerTransactions cannot be written to..
        /// </summary>
        internal static string E043Description {
            get {
                return ResourceManager.GetString("E043Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerTransactions cannot be written to..
        /// </summary>
        internal static string E043MessageFormat {
            get {
                return ResourceManager.GetString("E043MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InnerTransactions cannot be written to..
        /// </summary>
        internal static string E043Title {
            get {
                return ResourceManager.GetString("E043Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner transactions cannot be executed after the last assignment..
        /// </summary>
        internal static string E044Description {
            get {
                return ResourceManager.GetString("E044Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner transactions cannot be executed after the last assignment..
        /// </summary>
        internal static string E044MessageFormat {
            get {
                return ResourceManager.GetString("E044MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner transactions cannot be executed after the last assignment..
        /// </summary>
        internal static string E044Title {
            get {
                return ResourceManager.GetString("E044Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimisation step failed..
        /// </summary>
        internal static string E045Description {
            get {
                return ResourceManager.GetString("E045Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimisation step failed..
        /// </summary>
        internal static string E045MessageFormat {
            get {
                return ResourceManager.GetString("E045MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimisation step failed..
        /// </summary>
        internal static string E045Title {
            get {
                return ResourceManager.GetString("E045Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String method, property or field not supported..
        /// </summary>
        internal static string E046Description {
            get {
                return ResourceManager.GetString("E046Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String method, property or field not supported..
        /// </summary>
        internal static string E046MessageFormat {
            get {
                return ResourceManager.GetString("E046MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String method, property or field not supported..
        /// </summary>
        internal static string E046Title {
            get {
                return ResourceManager.GetString("E046Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property or field not supported..
        /// </summary>
        internal static string E047Description {
            get {
                return ResourceManager.GetString("E047Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property or field not supported..
        /// </summary>
        internal static string E047MessageFormat {
            get {
                return ResourceManager.GetString("E047MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property or field not supported..
        /// </summary>
        internal static string E047Title {
            get {
                return ResourceManager.GetString("E047Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported invocation {1}.
        /// </summary>
        internal static string E048Description {
            get {
                return ResourceManager.GetString("E048Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported invocation {1}.
        /// </summary>
        internal static string E048MessageFormat {
            get {
                return ResourceManager.GetString("E048MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported invocation {1}.
        /// </summary>
        internal static string E048Title {
            get {
                return ResourceManager.GetString("E048Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion to signed integer from decimal is not yet supported..
        /// </summary>
        internal static string E049Description {
            get {
                return ResourceManager.GetString("E049Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion to signed integer from decimal is not yet supported..
        /// </summary>
        internal static string E049MessageFormat {
            get {
                return ResourceManager.GetString("E049MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion to signed integer from decimal is not yet supported..
        /// </summary>
        internal static string E049Title {
            get {
                return ResourceManager.GetString("E049Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try statements cannot yet be supported..
        /// </summary>
        internal static string E051Description {
            get {
                return ResourceManager.GetString("E051Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try statements cannot yet be supported..
        /// </summary>
        internal static string E051MessageFormat {
            get {
                return ResourceManager.GetString("E051MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try statements cannot yet be supported..
        /// </summary>
        internal static string E051Title {
            get {
                return ResourceManager.GetString("E051Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This statement is not permitted in a stateless program..
        /// </summary>
        internal static string E052Description {
            get {
                return ResourceManager.GetString("E052Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This statement is not permitted in a stateless program..
        /// </summary>
        internal static string E052MessageFormat {
            get {
                return ResourceManager.GetString("E052MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This statement is not permitted in a stateless program..
        /// </summary>
        internal static string E052Title {
            get {
                return ResourceManager.GetString("E052Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This statement is not permitted in a smart contract..
        /// </summary>
        internal static string E053Description {
            get {
                return ResourceManager.GetString("E053Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This statement is not permitted in a smart contract..
        /// </summary>
        internal static string E053MessageFormat {
            get {
                return ResourceManager.GetString("E053MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This statement is not permitted in a smart contract..
        /// </summary>
        internal static string E053Title {
            get {
                return ResourceManager.GetString("E053Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvokeSmartSignatureMethod boilerplate used in incorrect scope..
        /// </summary>
        internal static string E054Description {
            get {
                return ResourceManager.GetString("E054Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvokeSmartSignatureMethod boilerplate used in incorrect scope.{1}.
        /// </summary>
        internal static string E054MessageFormat {
            get {
                return ResourceManager.GetString("E054MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvokeSmartSignatureMethod boilerplate used in incorrect scope..
        /// </summary>
        internal static string E054Title {
            get {
                return ResourceManager.GetString("E054Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Signature Methods must return an integer..
        /// </summary>
        internal static string E055Description {
            get {
                return ResourceManager.GetString("E055Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Signature Methods must return an integer..
        /// </summary>
        internal static string E055MessageFormat {
            get {
                return ResourceManager.GetString("E055MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Signature Methods must return an integer..
        /// </summary>
        internal static string E055Title {
            get {
                return ResourceManager.GetString("E055Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Signature Methods do not support Smart Contract References..
        /// </summary>
        internal static string E056Description {
            get {
                return ResourceManager.GetString("E056Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Signature Methods do not support Smart Contract References..
        /// </summary>
        internal static string E056MessageFormat {
            get {
                return ResourceManager.GetString("E056MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Signature Methods do not support Smart Contract References..
        /// </summary>
        internal static string E056Title {
            get {
                return ResourceManager.GetString("E056Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABI Structures cannot inherit in this version..
        /// </summary>
        internal static string E058Description {
            get {
                return ResourceManager.GetString("E058Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABI Structures cannot inherit in this version..
        /// </summary>
        internal static string E058MessageFormat {
            get {
                return ResourceManager.GetString("E058MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABI Structures cannot inherit in this version..
        /// </summary>
        internal static string E058Title {
            get {
                return ResourceManager.GetString("E058Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABI structures may not contain code..
        /// </summary>
        internal static string E059Description {
            get {
                return ResourceManager.GetString("E059Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABI structures may not contain code..
        /// </summary>
        internal static string E059MessageFormat {
            get {
                return ResourceManager.GetString("E059MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABI structures may not contain code..
        /// </summary>
        internal static string E059Title {
            get {
                return ResourceManager.GetString("E059Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABI struct fields must not be decorated..
        /// </summary>
        internal static string E060Description {
            get {
                return ResourceManager.GetString("E060Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABI struct fields must not be decorated..
        /// </summary>
        internal static string E060MessageFormat {
            get {
                return ResourceManager.GetString("E060MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABI struct fields must not be decorated..
        /// </summary>
        internal static string E060Title {
            get {
                return ResourceManager.GetString("E060Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate struct name {0}.
        /// </summary>
        internal static string E061Description {
            get {
                return ResourceManager.GetString("E061Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate struct name {0}.
        /// </summary>
        internal static string E061MessageFormat {
            get {
                return ResourceManager.GetString("E061MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate struct name {0}.
        /// </summary>
        internal static string E061Title {
            get {
                return ResourceManager.GetString("E061Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structs cannot be updated in this version..
        /// </summary>
        internal static string E062Description {
            get {
                return ResourceManager.GetString("E062Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structs cannot be updated in this version..
        /// </summary>
        internal static string E062MessageFormat {
            get {
                return ResourceManager.GetString("E062MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structs cannot be updated in this version..
        /// </summary>
        internal static string E062Title {
            get {
                return ResourceManager.GetString("E062Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version does not yet support application references to be accessed indirectly. Fields, properties and methods must be accessed directly from the declaring variable..
        /// </summary>
        internal static string E063Description {
            get {
                return ResourceManager.GetString("E063Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version does not yet support application references to be accessed indirectly. Fields, properties and methods must be accessed directly from the declaring variable..
        /// </summary>
        internal static string E063MessageFormat {
            get {
                return ResourceManager.GetString("E063MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version does not yet support application references to be accessed indirectly. Fields, properties and methods must be accessed directly from the declaring variable..
        /// </summary>
        internal static string E063Title {
            get {
                return ResourceManager.GetString("E063Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct not found..
        /// </summary>
        internal static string E064Description {
            get {
                return ResourceManager.GetString("E064Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct not found {0}.
        /// </summary>
        internal static string E064MessageFormat {
            get {
                return ResourceManager.GetString("E064MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct not found..
        /// </summary>
        internal static string E064Title {
            get {
                return ResourceManager.GetString("E064Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct field not found.
        /// </summary>
        internal static string E065Description {
            get {
                return ResourceManager.GetString("E065Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct field not found {0}.
        /// </summary>
        internal static string E065MessageFormat1 {
            get {
                return ResourceManager.GetString("E065MessageFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct field not found..
        /// </summary>
        internal static string E065Title1 {
            get {
                return ResourceManager.GetString("E065Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multidimensional arrays not yet supported..
        /// </summary>
        internal static string E066Description {
            get {
                return ResourceManager.GetString("E066Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multidimensional arrays not yet supported..
        /// </summary>
        internal static string E066MessageFormat {
            get {
                return ResourceManager.GetString("E066MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multidimensional arrays not yet supported..
        /// </summary>
        internal static string E066Title {
            get {
                return ResourceManager.GetString("E066Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array element type not yet supported..
        /// </summary>
        internal static string E067Description {
            get {
                return ResourceManager.GetString("E067Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array element type not yet supported..
        /// </summary>
        internal static string E067MessageFormat {
            get {
                return ResourceManager.GetString("E067MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array element type not yet supported..
        /// </summary>
        internal static string E067Title {
            get {
                return ResourceManager.GetString("E067Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABI return value must be the last parameter..
        /// </summary>
        internal static string E068Description {
            get {
                return ResourceManager.GetString("E068Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABI return value must be the last parameter..
        /// </summary>
        internal static string E068MessageFormat {
            get {
                return ResourceManager.GetString("E068MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABI return value must be the last parameter..
        /// </summary>
        internal static string E068Title {
            get {
                return ResourceManager.GetString("E068Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartContract Libraries cannot declare storage variables..
        /// </summary>
        internal static string E069Description {
            get {
                return ResourceManager.GetString("E069Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartContract Libraries cannot declare storage variables..
        /// </summary>
        internal static string E069MessageFormat {
            get {
                return ResourceManager.GetString("E069MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartContract Libraries cannot declare storage variables..
        /// </summary>
        internal static string E069Title {
            get {
                return ResourceManager.GetString("E069Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartContract Library methods must be static..
        /// </summary>
        internal static string E070Description {
            get {
                return ResourceManager.GetString("E070Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartContract Library methods must be static..
        /// </summary>
        internal static string E070MessageFormat {
            get {
                return ResourceManager.GetString("E070MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartContract Library methods must be static..
        /// </summary>
        internal static string E070Title {
            get {
                return ResourceManager.GetString("E070Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array initializers must be byte arrays in this version..
        /// </summary>
        internal static string E071Description {
            get {
                return ResourceManager.GetString("E071Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array initializers must be byte arrays in this version..
        /// </summary>
        internal static string E071MessageFormat {
            get {
                return ResourceManager.GetString("E071MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array initializers must be byte arrays in this version..
        /// </summary>
        internal static string E071Title {
            get {
                return ResourceManager.GetString("E071Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Algorand TEAL..
        /// </summary>
        internal static string I000Description {
            get {
                return ResourceManager.GetString("I000Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate &apos;{0}&apos; into Algorand TEAL.{1}.
        /// </summary>
        internal static string I000MessageFormat {
            get {
                return ResourceManager.GetString("I000MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEAL Generator.
        /// </summary>
        internal static string I000Title {
            get {
                return ResourceManager.GetString("I000Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration opcode size..
        /// </summary>
        internal static string I001Description {
            get {
                return ResourceManager.GetString("I001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opcode size for program {0}: {1}.
        /// </summary>
        internal static string I001MessageFormat {
            get {
                return ResourceManager.GetString("I001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delcaration opcode size..
        /// </summary>
        internal static string I001Title {
            get {
                return ResourceManager.GetString("I001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This scratch space variable is not shared across programs..
        /// </summary>
        internal static string W000Description {
            get {
                return ResourceManager.GetString("W000Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This scratch space variable {0} will not share values across programs.{1}.
        /// </summary>
        internal static string W000MessageFormat {
            get {
                return ResourceManager.GetString("W000MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared program scratch space variable..
        /// </summary>
        internal static string W000Title {
            get {
                return ResourceManager.GetString("W000Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognised syntax element omitted during compilation..
        /// </summary>
        internal static string W001Description {
            get {
                return ResourceManager.GetString("W001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognised syntax element {0} omitted during compilation.{1}.
        /// </summary>
        internal static string W001MessageFormat {
            get {
                return ResourceManager.GetString("W001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omitted syntax element..
        /// </summary>
        internal static string W001Title {
            get {
                return ResourceManager.GetString("W001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array initialisers will build arrays dynamically, costing opcodes. Please consider using the predefined array initialisation methods in IAlgorandCommonPredefineds instead..
        /// </summary>
        internal static string W002Description {
            get {
                return ResourceManager.GetString("W002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array initialisers will build arrays dynamically, costing opcodes. Please consider using the predefined array initialisation methods in IAlgorandCommonPredefineds instead.{1}.
        /// </summary>
        internal static string W002MessageFormat {
            get {
                return ResourceManager.GetString("W002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array initialisers are expensive..
        /// </summary>
        internal static string W002Title {
            get {
                return ResourceManager.GetString("W002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuppressNullableWarningExpression is ignored..
        /// </summary>
        internal static string W003Description {
            get {
                return ResourceManager.GetString("W003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuppressNullableWarningExpression is ignored.{1}.
        /// </summary>
        internal static string W003MessageFormat {
            get {
                return ResourceManager.GetString("W003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuppressNullableWarningExpression is ignored..
        /// </summary>
        internal static string W003Title {
            get {
                return ResourceManager.GetString("W003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inter-contract calls will be implemented in a future version..
        /// </summary>
        internal static string W004Description {
            get {
                return ResourceManager.GetString("W004Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inter-contract calls will be implemented in a future version.{1}.
        /// </summary>
        internal static string W004MessageFormat {
            get {
                return ResourceManager.GetString("W004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inter-contract calls will be implemented in a future version..
        /// </summary>
        internal static string W004Title {
            get {
                return ResourceManager.GetString("W004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code was generated for this syntax..
        /// </summary>
        internal static string W005Description {
            get {
                return ResourceManager.GetString("W005Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code was generated for this syntax.{0}.
        /// </summary>
        internal static string W005MessageFormat {
            get {
                return ResourceManager.GetString("W005MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code was generated for this syntax..
        /// </summary>
        internal static string W005Title {
            get {
                return ResourceManager.GetString("W005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported cast..
        /// </summary>
        internal static string W006Description {
            get {
                return ResourceManager.GetString("W006Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported cast.{0}.
        /// </summary>
        internal static string W006MessageFormat {
            get {
                return ResourceManager.GetString("W006MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported cast..
        /// </summary>
        internal static string W006Title {
            get {
                return ResourceManager.GetString("W006Title", resourceCulture);
            }
        }
    }
}
